/*-----------------------------------------------------------ITEM SOLD/PURCHASE/ADJUST/OUTSLIP/INSLIP PER PERIOD REPORT----------------------------------------------------------------------------*/
/*SALES*/
WITH
SALES AS (
		SELECT O.SUBSIDIARY_SID AS SBS_SID
			,O.STORE_SID
			,T.INVN_SBS_ITEM_SID AS ITEM_SID
			,SUM(CASE WHEN T.ITEM_TYPE = 1 THEN (T.QTY * - 1) ELSE T.QTY END) AS SOLD_QTY
		FROM RPS.DOCUMENT O
		LEFT JOIN RPS.DOCUMENT_ITEM T ON O.SID = T.DOC_SID
		WHERE T.ITEM_TYPE IN (1, 2)
			AND T.KIT_FLAG <> 3
			AND O.STATUS = 4
			AND O.IS_HELD <> 1
			AND O.DOC_NO > 0
			AND =-= TRUNC(o.CREATED_DATETIME) =-=
		GROUP BY O.SUBSIDIARY_SID
			,O.STORE_SID
			,T.INVN_SBS_ITEM_SID
		)
	,
	----------------------------------------------------
	/*PURCHASE*/
	PURCHASE AS (
		SELECT O.SBS_SID
			,O.STORE_SID
			,T.ITEM_SID
			,SUM(CASE WHEN O.VOU_TYPE = 1 THEN (T.QTY * - 1) ELSE T.QTY END) AS PURCHASED_QTY
		FROM RPS.VOUCHER O
		LEFT JOIN RPS.VOU_ITEM T ON O.SID = T.VOU_SID
		WHERE O.VOU_TYPE IN (0, 1)
			AND NVL(O.STATUS, 0) = 4
			AND NVL(O.VOU_NO, 0) > 0
			AND NVL(O.HELD, 0) = 0
			AND NVL(O.VOU_CLASS, 0) = 0
			AND NVL(O.REVERSED_FLAG, 0) = 0
			AND NVL(O.SLIP_FLAG, 0) = 0
			AND =-= TRUNC(o.CREATED_DATETIME) =-=
		GROUP BY O.SBS_SID
			,O.STORE_SID
			,T.ITEM_SID
		)
	,
	----------------------------------------------------
	/*INSLIP*/
	INSLIP AS (
		SELECT O.SBS_SID
			,O.STORE_SID
			,T.ITEM_SID
			,SUM(CASE WHEN O.VOU_TYPE = 1 THEN (T.QTY * - 1) ELSE T.QTY END) AS INSLIP_QTY
		FROM RPS.VOUCHER O
		LEFT JOIN RPS.VOU_ITEM T ON O.SID = T.VOU_SID
		WHERE O.VOU_TYPE IN (0, 1)
			AND NVL(O.STATUS, 0) = 4
			AND NVL(O.VOU_NO, 0) > 0
			AND NVL(O.HELD, 0) = 0
			AND NVL(O.VOU_CLASS, 0) = 0
			AND NVL(O.REVERSED_FLAG, 0) = 0
			AND NVL(O.SLIP_FLAG, 0) = 1
			AND =-= TRUNC(o.CREATED_DATETIME) =-=
		GROUP BY O.SBS_SID
			,O.STORE_SID
			,T.ITEM_SID
		)
	,
	------------------------------------------------ 
	/* ADJUSTMENT */
	ADJUST AS (
		SELECT O.SBS_SID
			,O.STORE_SID
			,T.ITEM_SID
			,SUM(NVL(T.ADJ_VALUE, 0) - NVL(T.ORIG_VALUE, 0)) AS ADJUST_QTY
		FROM RPS.ADJUSTMENT O
		LEFT JOIN RPS.ADJ_ITEM T ON O.SID = T.ADJ_SID
		WHERE NVL(O.ADJ_TYPE, 0) = 0
			AND NVL(O.HELD, 0) = 0
			AND NVL(O.STATUS, 0) = 4
			AND O.ADJ_NO > 0
			AND NVL(T.ITEM_NOTE1, 0) NOT LIKE 'PRISM%'
			AND =-= TRUNC(o.CREATED_DATETIME) =-=
		GROUP BY O.SBS_SID
			,O.STORE_SID
			,T.ITEM_SID
		)
	,
	------------------------------------------------ 
	/* OUTSLIP*/
	OUTSLIP AS (
		SELECT O.OUT_SBS_SID AS SBS_SID
			,O.OUT_STORE_SID AS STORE_SID
			,T.ITEM_SID
			,SUM(CASE WHEN NVL(O.REVERSED_FLAG, 0) = 2 THEN T.QTY ELSE T.QTY * - 1 END) AS OUTSLIP_QTY
		FROM RPS.SLIP O
		LEFT JOIN RPS.SLIP_ITEM T ON O.SID = T.SLIP_SID
		WHERE NVL(O.HELD, 0) = 0
			AND NVL(O.STATUS, 0) = 4
			AND NVL(O.SLIP_NO, 0) > 0
			AND =-= TRUNC(o.CREATED_DATETIME) =-=
		GROUP BY O.OUT_SBS_SID
			,O.OUT_STORE_SID
			,T.ITEM_SID
		)
	,
	--------------------------------------------------
	/*PRICE L 1*/
	PRICE1 AS (
		SELECT DISTINCT PR.PRICE
			,PR.INVN_SBS_ITEM_SID AS
		FROM RPS.INVN_SBS_PRICE PR
		INNER JOIN RPS.PRICE_LEVEL PL ON PL.SID = PR.PRICE_LVL_SID
		WHERE PL.PRICE_LVL = 1
		)
	,
	--------------------------------------------------
	/*PRICE L 2*/
	PRICE2 AS (
		SELECT DISTINCT PR.PRICE
			,PR.INVN_SBS_ITEM_SID AS
		FROM RPS.INVN_SBS_PRICE PR
		INNER JOIN RPS.PRICE_LEVEL PL ON PL.SID = PR.PRICE_LVL_SID
		WHERE PL.PRICE_LVL = 2
		)

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT SB.SBS_NO AS "Subsidiary No"
	,SB.SBS_NAME AS "Subsidiary Name"
	,ST.STORE_NO AS "Store No"
	,ST.STORE_CODE AS "Store Code"
	,ST.STORE_NAME AS "Store Name"
	,D.DCS_CODE AS "DCS Code"
	,V.VEND_CODE AS "Vendor Code"
	,V.VEND_NAME AS "Vendor Name"
	,I.ALU
	,TO_CHAR(I.UPC) AS UPC
	,I.DESCRIPTION1 AS "Description1"
	,I.DESCRIPTION2 AS "Description2"
	,I.DESCRIPTION3 AS "Description3"
	,I.DESCRIPTION4 AS "Description4"
	,I.ATTRIBUTE AS "Attribute"
	,I.ITEM_SIZE AS "Size"
	,I.COST AS "Cost"
	,NVL(P1.PRICE, 0) AS "Price1"
	,NVL(P2.PRICE, 0) AS "Price2"
	,SUM((NVL(S.SOLD_QTY, 0))) AS "Sold Qty"
	,SUM((NVL(P.PURCHASED_QTY, 0))) AS "Purchased Qty"
	,SUM((NVL(A.ADJUST_QTY, 0))) AS "Adjust Qty"
	,SUM((NVL(N.INSLIP_QTY, 0))) AS "Inslip Qty"
	,SUM((NVL(O.OUTSLIP_QTY, 0))) AS "Outslip Qty"
FROM RPS.INVN_SBS_ITEM_QTY IQ
LEFT JOIN RPS.INVN_SBS_ITEM I ON I.SBS_SID = IQ.SBS_SID
	AND I.SID = IQ.INVN_SBS_ITEM_SID
LEFT JOIN PRICE1 P1 ON P1.INVN_SBS_ITEM_SID = I.SID
LEFT JOIN PRICE2 P2 ON P2.INVN_SBS_ITEM_SID = I.SID
LEFT JOIN RPS.STORE ST ON IQ.SBS_SID = ST.SBS_SID
	AND IQ.STORE_SID = ST.SID
LEFT JOIN RPS.DCS D ON I.SBS_SID = D.SBS_SID
	AND I.DCS_SID = D.SID
LEFT JOIN RPS.VENDOR V ON V.SID = I.VEND_SID
LEFT JOIN SALES S ON S.SBS_SID = ST.SBS_SID
	AND S.ITEM_SID = I.SID
	AND S.STORE_SID = ST.SID
LEFT JOIN PURCHASE P ON P.SBS_SID = ST.SBS_SID
	AND P.ITEM_SID = I.SID
	AND P.STORE_SID = ST.SID
LEFT JOIN INSLIP N ON N.SBS_SID = ST.SBS_SID
	AND N.ITEM_SID = I.SID
	AND N.STORE_SID = ST.SID
LEFT JOIN ADJUST A ON A.SBS_SID = ST.SBS_SID
	AND A.ITEM_SID = I.SID
	AND A.STORE_SID = ST.SID
LEFT JOIN OUTSLIP O ON O.SBS_SID = ST.SBS_SID
	AND O.ITEM_SID = I.SID
	AND O.STORE_SID = ST.SID
LEFT JOIN RPS.SUBSIDIARY SB ON SB.SID = ST.SBS_SID
GROUP BY SB.SBS_NO
	,SB.SBS_NAME
	,ST.STORE_NO
	,ST.STORE_CODE
	,ST.STORE_NAME
	,D.DCS_CODE
	,V.VEND_CODE
	,V.VEND_NAME
	,I.ALU
	,I.UPC
	,I.DESCRIPTION1
	,I.DESCRIPTION2
	,I.DESCRIPTION3
	,I.DESCRIPTION4
	,I.ATTRIBUTE
	,I.ITEM_SIZE
	,I.COST
	,NVL(P1.PRICE, 0)
	,NVL(P2.PRICE, 0)
