SELECT S.SBS_NO AS "Subsidiary No"
	,S.SBS_NAME AS "Subsidiary Name"
	,D.DCS_CODE AS "DCS Code"
	,I.ALU AS ALU
	,TO_CHAR(I.UPC) AS UPC
	,V.VEND_CODE AS "Vendor Code"
	,V.VEND_NAME AS "Vendor Name"
	,D.D_NAME AS "Department"
	,D.C_NAME AS "Class"
	,D.S_NAME AS "SubClass"
	,I.DESCRIPTION1 AS "Description1"
	,I.DESCRIPTION2 AS "Description2"
	,I.DESCRIPTION3 AS "Description3"
	,I.DESCRIPTION4 AS "Description4"
	,I.ATTRIBUTE AS "Attribute"
	,I.ITEM_SIZE AS "Size"
	,I.UDF1_STRING AS "UDF1"
	,I.UDF2_STRING AS "UDF2"
	,I.UDF3_STRING AS "UDF3"
	,I.UDF4_STRING AS "UDF4"
	,I.UDF5_STRING AS "UDF5"
	,SUM(NVL(IQ.QTY, 0)) AS "OnHand Qty"
	,SUM(NVL(T.INTRANSIT_QTY, 0)) AS "InTransit Qty"
	,NVL(I.COST, 0) AS "Unit Cost"
	,NVL(IP1.PRICE,0) AS "Unit Price LVL1"
	,NVL(IP2.PRICE,0) AS "Unit Price LVL2"
	,NVL(IP3.PRICE,0) AS "Unit Price LVL3"
	,NVL(IP4.PRICE,0) AS "Unit Price LVL4"
	,SUM(NVL(IQ.QTY, 0) * NVL(IP1.PRICE,0)) AS "OnHand Total Price"
	,SUM(NVL(IQ.QTY, 0) * NVL(I.COST, 0)) AS "OnHand Total Cost"
	,SUM(NVL(T.INTRANSIT_QTY, 0) * NVL(IP1.PRICE,0)) AS "InTransit Total Price"
	,SUM(NVL(T.INTRANSIT_QTY, 0) * NVL(I.COST, 0)) AS "InTransit Total Cost"
	
FROM RPS.INVN_SBS_ITEM I
LEFT JOIN RPS.INVN_SBS_ITEM_QTY IQ ON I.SID = IQ.INVN_SBS_ITEM_SID
INNER JOIN RPS.SUBSIDIARY S ON S.SID = I.SBS_SID
INNER JOIN RPS.STORE ST ON ST.SID = IQ.STORE_SID
	AND ST.SBS_SID = S.SID
LEFT JOIN (
	SELECT DISTINCT PR.PRICE
		,PL.PRICE_LVL
		,PR.INVN_SBS_ITEM_SID
	FROM RPS.INVN_SBS_PRICE PR
	INNER JOIN RPS.PRICE_LEVEL PL ON PL.SID = PR.PRICE_LVL_SID
	WHERE PL.PRICE_LVL = 1
	) IP1 ON IP1.INVN_SBS_ITEM_SID = I.SID
LEFT JOIN (
	SELECT DISTINCT PR.PRICE
		,PL.PRICE_LVL
		,PR.INVN_SBS_ITEM_SID
	FROM RPS.INVN_SBS_PRICE PR
	INNER JOIN RPS.PRICE_LEVEL PL ON PL.SID = PR.PRICE_LVL_SID
	WHERE PL.PRICE_LVL = 2
	) IP2 ON IP2.INVN_SBS_ITEM_SID = I.SID
LEFT JOIN (
	SELECT DISTINCT PR.PRICE
		,PL.PRICE_LVL
		,PR.INVN_SBS_ITEM_SID
	FROM RPS.INVN_SBS_PRICE PR
	INNER JOIN RPS.PRICE_LEVEL PL ON PL.SID = PR.PRICE_LVL_SID
	WHERE PL.PRICE_LVL = 3
	) IP3 ON IP3.INVN_SBS_ITEM_SID = I.SID
LEFT JOIN (
	SELECT DISTINCT PR.PRICE
		,PL.PRICE_LVL
		,PR.INVN_SBS_ITEM_SID
	FROM RPS.INVN_SBS_PRICE PR
	INNER JOIN RPS.PRICE_LEVEL PL ON PL.SID = PR.PRICE_LVL_SID
	WHERE PL.PRICE_LVL = 4
	) IP4 ON IP4.INVN_SBS_ITEM_SID = I.SID
LEFT JOIN RPS.VENDOR V ON I.VEND_SID = V.SID
LEFT JOIN RPS.DCS D ON I.DCS_SID = D.SID
LEFT JOIN (
	SELECT S.IN_STORE_SID AS STORE_SID
		,S.IN_SBS_SID AS SBS_SID
		,SI.ITEM_SID
		,SUM(SI.QTY) AS INTRANSIT_QTY
	FROM RPS.SLIP S
	LEFT JOIN RPS.SLIP_ITEM SI ON S.SID = SI.SLIP_SID
	LEFT JOIN RPS.VOUCHER V ON S.VOU_SID = V.SID
	WHERE S.HELD = 0
		AND S.SLIP_NO <> 0
		AND S.STATUS = 4
		AND V.STATUS = 3
		AND NVL(S.REVERSED_FLAG, 0) = 0
	GROUP BY S.IN_STORE_SID
		,S.IN_SBS_SID
		,SI.ITEM_SID
	) T ON T.ITEM_SID = I.SID
	AND T.STORE_SID = ST.SID
	AND S.SID = T.SBS_SID
GROUP BY S.SBS_NO
	,S.SBS_NAME
	,D.DCS_CODE
	,I.ALU
	,I.UPC
	,V.VEND_CODE
	,V.VEND_NAME
	,D.D_NAME
	,D.C_NAME
	,D.S_NAME
	,I.DESCRIPTION1
	,I.DESCRIPTION2
	,I.DESCRIPTION3
	,I.DESCRIPTION4
	,I.ATTRIBUTE
	,I.ITEM_SIZE
	,I.UDF1_STRING
	,I.UDF2_STRING
	,I.UDF3_STRING
	,I.UDF4_STRING
	,I.UDF5_STRING
	,NVL(I.COST, 0)
	,NVL(IP1.PRICE,0)
	,NVL(IP2.PRICE,0)
	,NVL(IP3.PRICE,0)
	,NVL(IP4.PRICE,0)
