SELECT N.CREATED_DATETIME AS "Created At"
	,N.CREATED_BY AS "Created By"
	,N.MODIFIED_DATETIME AS "Modified At"
	,N.MODIFIED_BY AS "Modified By"
	,SB.SBS_NO AS "Subsidiary No"
	,SB.SBS_NAME AS "Subsidiary Name"
	,V.VEND_CODE AS "Vendor Code"
	,V.VEND_NAME AS "Vendor Name"
	,DC.DCS_CODE AS "DCS Code"
	,DC.D_NAME AS "Department Name"
	,DC.C_NAME AS "Class Name"
	,DC.S_NAME AS "SubClass Name"
	,TO_CHAR(N.SID) AS "Item SID"
	,TO_CHAR(N.INVN_ITEM_UID) AS "Item UID"
	,TO_CHAR(N.ALU) AS ALU
	,TO_CHAR(N.UPC) AS UPC
	,N.DESCRIPTION1 AS "Description1"
	,N.DESCRIPTION2 AS "Description2"
	,N.DESCRIPTION3 AS "Description3"
	,N.DESCRIPTION4 AS "Description4"
	,N.LONG_DESCRIPTION AS "Long Description"
	,N.ATTRIBUTE AS "Attribute"
	,N.ITEM_SIZE AS "Size"
	,N.LAST_SOLD_DATE AS "Last Sold Date"
	,N.FIRST_RCVD_DATE AS "First Receive Date"
	,N.LAST_RCVD_DATE AS "Last Receive Date"
	,N.MAX_DISC_PERC1 AS "Max Discount Percentage1"
	,N.MAX_DISC_PERC2 AS "Max Discount Percentage2"
	,CASE 
		WHEN N.KIT_TYPE = 0
			THEN 'Normal'
		WHEN N.KIT_TYPE = 1
			THEN 'Kit'
		WHEN N.KIT_TYPE = 2
			THEN 'Package'
		WHEN N.KIT_TYPE = 3
			THEN 'GiftCardStoredValue'
		WHEN N.KIT_TYPE = 4
			THEN 'GiftCardPrePaid'
		WHEN N.KIT_TYPE = 5
			THEN 'GiftCertificate'
		WHEN N.KIT_TYPE = 6
			THEN 'Fee'
		WHEN N.KIT_TYPE = 7
			THEN 'GiftCardCentral'
		END AS "Kit Type"
	,CASE 
		WHEN N.NON_INVENTORY = 1
			THEN 'Non-Inventory'
		ELSE 'Inventory'
		END AS "Inventory Type"
	,N.TEXT1 AS "Text1"
	,N.TEXT2 AS "Text2"
	,N.TEXT3 AS "Text3"
	,N.TEXT4 AS "Text4"
	,N.TEXT5 AS "Text5"
	,N.TEXT6 AS "Text6"
	,N.TEXT7 AS "Text7"
	,N.TEXT8 AS "Text8"
	,N.TEXT9 AS "Text9"
	,N.TEXT10 AS "Text10"
	,N.UDF1_STRING AS "UDF1"
	,N.UDF2_STRING AS "UDF2"
	,N.UDF3_STRING AS "UDF3"
	,N.UDF4_STRING AS "UDF4"
	,N.UDF5_STRING AS "UDF5"
	,UD.UDF6_STRING AS "UDF6"
	,UD.UDF7_STRING AS "UDF7"
	,UD.UDF8_STRING AS "UDF8"
	,UD.UDF9_STRING AS "UDF9"
	,UD.UDF10_STRING AS "UDF10"
	,UD.UDF11_STRING AS "UDF11"
	,UD.UDF12_STRING AS "UDF12"
	,UD.UDF13_STRING AS "UDF13"
	,UD.UDF14_STRING AS "UDF14"
	,UD.UDF15_STRING AS "UDF15"
	,N.COST AS "Cost"
	,CASE 
		WHEN N.ACTIVE = 1
			THEN 'Active'
		ELSE 'Inactive'
		END AS "Activity Status"
	,P1.PRICE AS "Price LVL1"
	,P2.PRICE AS "Price LVL2"
	,P3.PRICE AS "Price LVL3"
	,P4.PRICE AS "Price LVL4"
FROM RPS.INVN_SBS_ITEM N
LEFT JOIN RPS.SUBSIDIARY SB ON SB.SID = N.SBS_SID
LEFT JOIN RPS.DCS DC ON DC.SID = N.DCS_SID
	AND DC.SBS_SID = N.SBS_SID
LEFT JOIN RPS.VENDOR V ON V.SID = N.VEND_SID
	AND V.SBS_SID = N.SBS_SID
LEFT JOIN RPS.INVN_SBS_EXTEND UD ON UD.INVN_SBS_ITEM_SID = N.SID
LEFT JOIN (
	SELECT DISTINCT PR.PRICE
		,PR.INVN_SBS_ITEM_SID
	FROM RPS.INVN_SBS_PRICE PR
	INNER JOIN RPS.PRICE_LEVEL PL ON PL.SID = PR.PRICE_LVL_SID
	WHERE PL.PRICE_LVL = 1
	) P1 ON P1.INVN_SBS_ITEM_SID = N.SID
LEFT JOIN (
	SELECT DISTINCT PR.PRICE
		,PR.INVN_SBS_ITEM_SID
	FROM RPS.INVN_SBS_PRICE PR
	INNER JOIN RPS.PRICE_LEVEL PL ON PL.SID = PR.PRICE_LVL_SID
	WHERE PL.PRICE_LVL = 2
	) P2 ON P2.INVN_SBS_ITEM_SID = N.SID
LEFT JOIN (
	SELECT DISTINCT PR.PRICE
		,PR.INVN_SBS_ITEM_SID
	FROM RPS.INVN_SBS_PRICE PR
	INNER JOIN RPS.PRICE_LEVEL PL ON PL.SID = PR.PRICE_LVL_SID
	WHERE PL.PRICE_LVL = 3
	) P3 ON P3.INVN_SBS_ITEM_SID = N.SID
LEFT JOIN (
	SELECT DISTINCT PR.PRICE
		,PR.INVN_SBS_ITEM_SID
	FROM RPS.INVN_SBS_PRICE PR
	INNER JOIN RPS.PRICE_LEVEL PL ON PL.SID = PR.PRICE_LVL_SID
	WHERE PL.PRICE_LVL = 4
	) P4 ON P4.INVN_SBS_ITEM_SID = N.SID
ORDER BY SB.SBS_NO
