/*-----------------------------------------------------------ITEM OH/SOLD/PURCHASE/ADJUST/OUTSLIP/INSLIP/INTRANS REPORT----------------------------------------------------------------------------*/

/*INTRANSIT*/
WITH INTRANSIT AS (SELECT
             S.IN_STORE_SID AS STORE_SID,
             S.IN_SBS_SID AS SBS_SID,
             SI.ITEM_SID,
             SUM(SI.QTY) AS INTRANSIT_QTY
  FROM RPS.SLIP S
    LEFT OUTER JOIN RPS.SLIP_ITEM SI
      ON S.SID = SI.SLIP_SID
    LEFT OUTER JOIN RPS.VOUCHER V
      ON S.VOU_SID = V.SID
  WHERE S.HELD = 0
    AND S.SLIP_NO <> 0
               AND S.STATUS = 4
               AND V.STATUS = 3
               AND NVL(S.REVERSED_FLAG,0)=0
  GROUP BY  S.IN_STORE_SID, S.IN_SBS_SID, SI.ITEM_SID),
----------------------------------------------------
/*SALES*/
SALES AS (SELECT 
        O.SUBSIDIARY_SID AS SBS_SID,
        O.STORE_SID,
        T.INVN_SBS_ITEM_SID   AS ITEM_SID,
        SUM(CASE WHEN T.ITEM_TYPE = 1 THEN  (T.QTY * -1) ELSE T.QTY END) AS SOLD_QTY
  FROM RPS.DOCUMENT O LEFT JOIN RPS.DOCUMENT_ITEM T ON O.SID = T.DOC_SID
WHERE     T.ITEM_TYPE IN (1, 2)
       AND T.KIT_FLAG <> 3
       AND O.STATUS = 4
       AND O.IS_HELD <> 1
       AND O.DOC_NO > 0
GROUP BY  O.SUBSIDIARY_SID, O.STORE_SID, T.INVN_SBS_ITEM_SID),
----------------------------------------------------
/*PURCHASE*/
PURCHASE AS (SELECT 
       O.SBS_SID,
       O.STORE_SID,
       T.ITEM_SID,
      SUM( CASE WHEN O.VOU_TYPE = 1 THEN  (T.QTY * -1) ELSE T.QTY END)   AS PURCHASED_QTY
  FROM RPS.VOUCHER O LEFT JOIN RPS.VOU_ITEM T ON O.SID = T.VOU_SID
WHERE     O.VOU_TYPE IN (0, 1)
       AND NVL (O.STATUS, 0) = 4
       AND NVL (O.VOU_NO, 0) > 0
       AND NVL (O.HELD, 0) = 0
       AND NVL (O.VOU_CLASS, 0) = 0
       AND NVL (O.REVERSED_FLAG, 0) = 0
       AND NVL(O.SLIP_FLAG,0) = 0
GROUP BY  O.SBS_SID, O.STORE_SID,T.ITEM_SID),
----------------------------------------------------
/*INSLIP*/
INSLIP AS (SELECT 
       O.SBS_SID,
       O.STORE_SID,
       T.ITEM_SID,
      SUM( CASE WHEN O.VOU_TYPE = 1 THEN  (T.QTY * -1) ELSE T.QTY END)   AS INSLIP_QTY
  FROM RPS.VOUCHER O LEFT JOIN RPS.VOU_ITEM T ON O.SID = T.VOU_SID
WHERE     O.VOU_TYPE IN (0, 1)
       AND NVL (O.STATUS, 0) = 4
       AND NVL (O.VOU_NO, 0) > 0
       AND NVL (O.HELD, 0) = 0
       AND NVL (O.VOU_CLASS, 0) = 0
       AND NVL (O.REVERSED_FLAG, 0) = 0
       AND NVL(O.SLIP_FLAG,0) = 1
GROUP BY  O.SBS_SID, O.STORE_SID,T.ITEM_SID),
------------------------------------------------ 
/* ADJUSTMENT */
       ADJUST AS (SELECT
       O.SBS_SID,
       O.STORE_SID,
       T.ITEM_SID,
      SUM( NVL(T.ADJ_VALUE, 0) - NVL(T.ORIG_VALUE, 0)) AS ADJUST_QTY
  FROM RPS.ADJUSTMENT O LEFT JOIN RPS.ADJ_ITEM T ON O.SID = T.ADJ_SID
WHERE     NVL (O.ADJ_TYPE, 0) = 0
       AND NVL (O.HELD, 0) = 0
       AND NVL (O.STATUS, 0) = 4
       AND O.ADJ_NO > 0
       AND NVL (T.ITEM_NOTE1, 0) NOT LIKE 'PRISM%'
GROUP BY  O.SBS_SID, O.STORE_SID,T.ITEM_SID ),
  ------------------------------------------------ 
/* OUTSLIP*/
       OUTSLIP AS (SELECT
       O.OUT_SBS_SID       AS SBS_SID,
       O.OUT_STORE_SID     AS STORE_SID,
       T.ITEM_SID,
       SUM(CASE WHEN NVL (O.REVERSED_FLAG, 0) = 2 THEN T.QTY ELSE T.QTY*-1 END) AS OUTSLIP_QTY
  FROM RPS.SLIP O LEFT JOIN RPS.SLIP_ITEM T ON O.SID = T.SLIP_SID
WHERE     NVL (O.HELD, 0) = 0
       AND NVL (O.STATUS, 0) = 4
       AND NVL (O.SLIP_NO, 0) > 0
GROUP BY  O.OUT_SBS_SID, O.OUT_STORE_SID,T.ITEM_SID),
--------------------------------------------------
/*PRICE L 1*/
        PRICE1 AS (SELECT 
        DISTINCT PR.PRICE
       ,PR.INVN_SBS_ITEM_SID AS 
  FROM RPS.INVN_SBS_PRICE PR
  INNER JOIN RPS.PRICE_LEVEL PL
  ON PL.SID = PR.PRICE_LVL_SID
WHERE PL.PRICE_LVL = 1),
--------------------------------------------------
/*PRICE L 2*/
        PRICE2 AS (SELECT 
        DISTINCT PR.PRICE
       ,PR.INVN_SBS_ITEM_SID AS 
  FROM RPS.INVN_SBS_PRICE PR
  INNER JOIN RPS.PRICE_LEVEL PL
  ON PL.SID = PR.PRICE_LVL_SID
WHERE PL.PRICE_LVL = 2)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT SB.SBS_NO As "Subsidiary No",SB.SBS_NAME As "Subsidiary Name" ,D.DCS_CODE As "DCS Code" ,V.VEND_CODE AS "Vendor Code",V.VEND_NAME AS "Vendor Name",
I.ALU,TO_CHAR(I.UPC) As UPC,I.DESCRIPTION1 As "Description1",I.DESCRIPTION2 As "Description2",I.DESCRIPTION3 As "Description3",I.DESCRIPTION4 As "Description4",I.ATTRIBUTE as "Attribute",I.ITEM_SIZE as "Size",I.COST As "Cost",
NVL(P1.PRICE,0) AS "Price1",NVL(P2.PRICE,0) AS "Price2",SUM(NVL(IQ.QTY,0)) AS "OnHand Qty",
SUM((NVL(S.SOLD_QTY,0))) AS "Sold Qty",SUM((NVL(P.PURCHASED_QTY,0)))  AS "Purchased Qty" ,
SUM((NVL(A.ADJUST_QTY,0))) AS "Adjust Qty" ,SUM((NVL(N.INSLIP_QTY,0)))  AS "Inslip Qty" ,
SUM((NVL(O.OUTSLIP_QTY,0)))  AS "Outslip Qty" ,SUM((NVL(T.INTRANSIT_QTY,0))) AS "Intransit Qty" 

FROM RPS.INVN_SBS_ITEM_QTY IQ
LEFT JOIN RPS.INVN_SBS_ITEM I          ON I.SBS_SID = IQ.SBS_SID AND I.SID = IQ.INVN_SBS_ITEM_SID 
LEFT JOIN PRICE1 P1           ON P1.INVN_SBS_ITEM_SID = I.SID
LEFT JOIN PRICE2 P2           ON P2.INVN_SBS_ITEM_SID = I.SID
LEFT JOIN RPS.STORE ST          ON IQ.SBS_SID = ST.SBS_SID AND IQ.STORE_SID = ST.SID    
LEFT JOIN RPS.DCS D          ON I.SBS_SID = D.SBS_SID AND I.DCS_SID = D.SID
LEFT JOIN RPS.VENDOR V             ON V.SID = I.VEND_SID 
LEFT JOIN SALES S          ON  S.SBS_SID = ST.SBS_SID AND S.ITEM_SID = I.SID  AND S.STORE_SID = ST.SID
LEFT JOIN PURCHASE  P          ON  P.SBS_SID = ST.SBS_SID AND P.ITEM_SID = I.SID  AND P.STORE_SID = ST.SID
LEFT JOIN INSLIP  N          ON  N.SBS_SID = ST.SBS_SID AND N.ITEM_SID = I.SID  AND N.STORE_SID = ST.SID
LEFT JOIN ADJUST A        ON  A.SBS_SID = ST.SBS_SID AND A.ITEM_SID = I.SID  AND A.STORE_SID = ST.SID
LEFT JOIN OUTSLIP O          ON  O.SBS_SID = ST.SBS_SID AND O.ITEM_SID = I.SID  AND O.STORE_SID = ST.SID
LEFT JOIN INTRANSIT T          ON  T.SBS_SID = ST.SBS_SID AND T.ITEM_SID = I.SID  AND T.STORE_SID = ST.SID
LEFT JOIN RPS.SUBSIDIARY SB        ON  SB.SID = ST.SBS_SID

GROUP BY SB.SBS_NO,SB.SBS_NAME,D.DCS_CODE ,V.VEND_CODE,V.VEND_NAME,
I.ALU,I.UPC ,I.DESCRIPTION1,I.DESCRIPTION2,I.DESCRIPTION3,I.DESCRIPTION4,I.ATTRIBUTE,I.ITEM_SIZE,I.COST,
NVL(P1.PRICE,0),NVL(P2.PRICE,0)