SELECT D.SBS_NO AS "Subsidiary No"
	,TRUNC(D.INVC_POST_DATE) AS "Post Date"
	,SUM(CASE 
			WHEN D.RECEIPT_TYPE = 0
				THEN 1
			ELSE 0
			END) AS "#Sales Invoices"
	,SUM(CASE 
			WHEN D.RECEIPT_TYPE = 1
				THEN 1
			ELSE 0
			END) AS "#Return Invoices"
	,SUM(CASE 
			WHEN D.RECEIPT_TYPE = 2
				THEN 1
			ELSE 0
			END) AS "#Order Invoices"
	,SUM((NVL(D.SALE_SUBTOTAL_WITH_TAX, 0) - NVL(D.SALE_TOTAL_TAX_AMT, 0)) - (NVL(D.RETURN_SUBTOTAL_WITH_TAX, 0) - NVL(D.RETURN_TOTAL_TAX_AMT, 0))) AS "Net Sales"
	,SUM(NVL(D.DISC_AMT, 0)) AS "Invoice Discount "
	,SUM(NVL(D.SALE_TOTAL_TAX_AMT, 0) - NVL(D.RETURN_TOTAL_TAX_AMT, 0)) AS "Total Tax"
	,SUM(NVL(D.TOTAL_DEPOSIT_TAKEN, 0)) AS "Total Deposit"
	,SUM(NVL(D.TOTAL_FEE_AMT, 0)) AS "Total Fees"
	,SUM(NVL(D.shipping_amt, 0)) AS "Total Shipping"
	,SUM((NVL(D.SALE_SUBTOTAL_WITH_TAX, 0) - NVL(D.RETURN_SUBTOTAL_WITH_TAX, 0)) + (NVL(D.TOTAL_DEPOSIT_TAKEN, 0)) + (NVL(D.TOTAL_FEE_AMT, 0)) + NVL(D.shipping_amt, 0)) AS "Total Transaction WTax"
FROM RPS.DOCUMENT D
INNER JOIN RPS.STORE ST ON ST.SID = D.STORE_SID
WHERE D.STATUS = 4
GROUP BY D.SBS_NO
	,TRUNC(D.INVC_POST_DATE)
ORDER BY TRUNC(D.INVC_POST_DATE) DESC
	,D.SBS_NO
