SELECT 
     D.SBS_NO AS "Subsidiary No"
	,ST.STORE_CODE AS "Store Code"
	,ST.STORE_NAME AS "Store Name"
	,TRUNC(D.INVC_POST_DATE) AS "Post Date"
	,D.DOC_NO AS "Document No"
	,D.ORDER_DOC_NO AS "Order Document No"
	,CASE 
		WHEN D.RECEIPT_TYPE = 0
			THEN 'Sale'
		WHEN D.RECEIPT_TYPE = 1
			THEN 'Return'
		ELSE 'Order'
		END AS "Invoice Type"
	,(NVL(D.SALE_SUBTOTAL_WITH_TAX,0)-NVL( D.SALE_TOTAL_TAX_AMT,0)) - (NVL(D.RETURN_SUBTOTAL_WITH_TAX,0) - NVL(D.RETURN_TOTAL_TAX_AMT,0)) AS "Net Sales"
	,NVL(D.SALE_TOTAL_TAX_AMT,0) - NVL(D.RETURN_TOTAL_TAX_AMT,0) AS "Total Tax"
	,NVL(D.DISC_AMT, 0) AS "Invoice Discount "
	,NVL(D.TOTAL_DEPOSIT_TAKEN, 0) AS "Total Deposit"
	,NVL(D.TOTAL_FEE_AMT, 0) AS "Total Fees"
    ,NVL(D.shipping_amt, 0) AS "Total Shipping"
	,((NVL(D.SALE_SUBTOTAL_WITH_TAX,0) - NVL(D.RETURN_SUBTOTAL_WITH_TAX,0)) + (NVL(D.TOTAL_DEPOSIT_TAKEN, 0)) + (NVL(D.TOTAL_FEE_AMT, 0))+ NVL(D.shipping_amt, 0))  AS "Total Transaction WTax"
FROM RPS.DOCUMENT D
INNER JOIN RPS.STORE ST ON ST.SID = D.STORE_SID
WHERE D.STATUS = 4

ORDER BY D.STORE_CODE
	,INVC_POST_DATE