-----YTD SALE----
WITH YTD
AS (
	SELECT D.STORE_SID
		,SUM((NVL(D.SALE_SUBTOTAL_WITH_TAX, 0) - NVL(D.RETURN_SUBTOTAL_WITH_TAX, 0)) + (NVL(D.TOTAL_DEPOSIT_TAKEN, 0)) + (NVL(D.TOTAL_FEE_AMT, 0)) + NVL(D.shipping_amt, 0)) AS SALES
	FROM RPS.DOCUMENT D
	WHERE D.STATUS = 4
		AND EXTRACT(YEAR FROM D.INVC_POST_DATE) = EXTRACT(YEAR FROM SYSDATE)
	GROUP BY D.STORE_SID
	)
	,
	----MTD SALES----
MTD
AS (
	SELECT D.STORE_SID
		,SUM((NVL(D.SALE_SUBTOTAL_WITH_TAX, 0) - NVL(D.RETURN_SUBTOTAL_WITH_TAX, 0)) + (NVL(D.TOTAL_DEPOSIT_TAKEN, 0)) + (NVL(D.TOTAL_FEE_AMT, 0)) + NVL(D.shipping_amt, 0)) AS SALES
	FROM RPS.DOCUMENT D
	WHERE D.STATUS = 4
		AND EXTRACT(YEAR FROM D.INVC_POST_DATE) = EXTRACT(YEAR FROM SYSDATE)
		AND EXTRACT(MONTH FROM D.INVC_POST_DATE) = EXTRACT(MONTH FROM SYSDATE)
	GROUP BY D.STORE_SID
	)
	,
	----YESTERDAY SALES----
YDAY
AS (
	SELECT D.STORE_SID
		,SUM((NVL(D.SALE_SUBTOTAL_WITH_TAX, 0) - NVL(D.RETURN_SUBTOTAL_WITH_TAX, 0)) + (NVL(D.TOTAL_DEPOSIT_TAKEN, 0)) + (NVL(D.TOTAL_FEE_AMT, 0)) + NVL(D.shipping_amt, 0)) AS SALES
	FROM RPS.DOCUMENT D
	WHERE D.STATUS = 4
		AND TRUNC(D.INVC_POST_DATE) = TRUNC(SYSDATE - 1)
	GROUP BY D.STORE_SID
	)
	,
	----TODAY SALES----
TODAY
AS (
	SELECT D.STORE_SID
		,SUM((NVL(D.SALE_SUBTOTAL_WITH_TAX, 0) - NVL(D.RETURN_SUBTOTAL_WITH_TAX, 0)) + (NVL(D.TOTAL_DEPOSIT_TAKEN, 0)) + (NVL(D.TOTAL_FEE_AMT, 0)) + NVL(D.shipping_amt, 0)) AS SALES
	FROM RPS.DOCUMENT D
	WHERE D.STATUS = 4
		AND TRUNC(D.INVC_POST_DATE) = TRUNC(SYSDATE)
	GROUP BY D.STORE_SID
	)
	,
	----TOTAL SALES----
TOTAL
AS (
	SELECT D.STORE_SID
		,SUM((NVL(D.SALE_SUBTOTAL_WITH_TAX, 0) - NVL(D.RETURN_SUBTOTAL_WITH_TAX, 0)) + (NVL(D.TOTAL_DEPOSIT_TAKEN, 0)) + (NVL(D.TOTAL_FEE_AMT, 0)) + NVL(D.shipping_amt, 0)) AS SALES
	FROM RPS.DOCUMENT D
	WHERE D.STATUS = 4
	GROUP BY D.STORE_SID
	)
---------------------------
SELECT SB.SBS_NO AS "Subsidiary No"
	,SB.SBS_Name AS "Subsidiary Name"
	,St.Store_NO AS "Store No"
	,St.Store_code AS "Store Code"
	,St.Store_Name AS "Store Name"
	,NVL(TODAY.SALES, 0) AS "Today Sales"
	,NVL(YDAY.SALES, 0) AS "Yesterday Sales"
	,NVL(MTD.SALES, 0) AS "MTD Sales"
	,NVL(YTD.SALES, 0) AS "YTD Sales"
	,NVL(TOTAL.SALES, 0) AS "Total Sales"
FROM RPS.STORE ST
INNER JOIN RPS.SUBSIDIARY SB ON ST.SBS_SID = SB.SID
LEFT JOIN YTD ON ST.SID = YTD.STORE_SID
LEFT JOIN MTD ON ST.SID = MTD.STORE_SID
LEFT JOIN YDAY ON ST.SID = YDAY.STORE_SID
LEFT JOIN TODAY ON ST.SID = TODAY.STORE_SID
LEFT JOIN TOTAL ON ST.SID = TOTAL.STORE_SID
ORDER BY SB.SBS_NO
	,ST.STORE_CODE
