SELECT *
FROM (
	SELECT S.sbs_no AS "Subsidiary No"
	     ,ST.STORE_CODE AS "Store Code"
		,ST.STORE_NAME AS "Store Name"
		,D.DCS_CODE AS "DCS Code"
		,I.ALU
		,TO_CHAR(I.UPC) AS UPC
		,I.DESCRIPTION1 AS "Description1"
		,I.DESCRIPTION2 AS "Description2"
		,I.DESCRIPTION3 AS "Description3"
		,I.DESCRIPTION4 AS "Description4"
		,I.ITEM_SIZE AS "Size"
		,I.ATTRIBUTE AS "Attribute"
		,V.VEND_CODE AS "Vendor Code"
		,V.VEND_NAME AS "Vendor Name"
		,I.LAST_SOLD_DATE AS "Co Last Sold Date"
		,SUM(NVL(IQ.QTY, 0)) AS "OnHand Qty"
		,ROUND(SUM(NVL(IQ.QTY, 0) * NVL(IP.PRICE, 0)), 2) AS "OnHand Ext Price"
		,SUM(NVL(SAL.QTY, 0)) AS "Sold Qty"
		,ROUND(SUM(NVL(SAL.VAL, 0)), 2) AS "Sold Value"
		,DENSE_RANK() OVER (
			PARTITION BY S.SBS_NO,ST.STORE_CODE ORDER BY SUM(NVL(IQ.QTY, 0)) DESC
			) AS "Rank"
	FROM RPS.INVN_SBS_ITEM I
	INNER JOIN RPS.SUBSIDIARY S ON I.SBS_SID = S.SID
	LEFT JOIN RPS.VENDOR V ON V.SID = I.VEND_SID
	INNER JOIN RPS.INVN_SBS_ITEM_QTY IQ ON I.SBS_SID = IQ.SBS_SID
		AND I.SID = IQ.INVN_SBS_ITEM_SID
	INNER JOIN RPS.STORE ST ON IQ.SBS_SID = ST.SBS_SID
		AND IQ.STORE_SID = ST.SID
		AND S.SID = ST.SBS_SID
	INNER JOIN RPS.DCS D ON I.SBS_SID = D.SBS_SID
		AND I.DCS_SID = D.SID
	LEFT JOIN (
		SELECT DISTINCT PR.PRICE
			,PR.INVN_SBS_ITEM_SID
		FROM RPS.INVN_SBS_PRICE PR
		INNER JOIN RPS.PRICE_LEVEL PL ON PL.SID = PR.PRICE_LVL_SID
		WHERE PL.PRICE_LVL = 1
		) IP ON I.SID = IP.INVN_SBS_ITEM_SID
	LEFT JOIN (
		SELECT A.SBS_NO
			,A.STORE_SID
			,B.INVN_SBS_ITEM_SID
			,SUM(DECODE(B.ITEM_TYPE, 2, B.QTY * - 1, B.QTY)) QTY
			,SUM(DECODE(B.ITEM_TYPE, 2, B.QTY * - 1, B.QTY) * (CASE WHEN A.USE_VAT = 0 THEN (B.PRICE + B.TAX_AMT) ELSE B.PRICE END)) VAL
		FROM RPS.DOCUMENT A
			,RPS.DOCUMENT_ITEM B
		WHERE A.SID = B.DOC_SID
			AND B.ITEM_TYPE IN (1,2)
			AND A.STATUS = 4
			AND =-= TRUNC(A.invc_post_date) =-=
		GROUP BY A.SBS_NO
			,A.STORE_SID
			,B.INVN_SBS_ITEM_SID
		) SAL ON S.SBS_NO = SAL.SBS_NO
		AND IQ.STORE_SID = SAL.STORE_SID
		AND IQ.INVN_SBS_ITEM_SID = SAL.INVN_SBS_ITEM_SID
	WHERE 1 = 1
	GROUP BY S.SBS_NO
	    ,ST.STORE_NAME
		,ST.STORE_CODE
		,D.DCS_CODE
		,I.ALU
		,I.UPC
		,I.DESCRIPTION1
		,I.DESCRIPTION2
        ,I.DESCRIPTION3
		,I.DESCRIPTION4
		,I.ITEM_SIZE
		,I.ATTRIBUTE 
		,V.VEND_CODE 
		,V.VEND_NAME 
		,I.LAST_SOLD_DATE
	)
WHERE 1 = 1
